//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.18 at 08:28:08 PM MESZ 
//


package com.kellnersystem.main;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tisch" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Bestellungen">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Bestellung" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Artikellist">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Artikel" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="Artikel_id">
 *                                                             &lt;simpleType>
 *                                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                                                 &lt;minInclusive value="0"/>
 *                                                               &lt;/restriction>
 *                                                             &lt;/simpleType>
 *                                                           &lt;/element>
 *                                                           &lt;element name="Menge">
 *                                                             &lt;simpleType>
 *                                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                                                 &lt;minInclusive value="0"/>
 *                                                               &lt;/restriction>
 *                                                             &lt;/simpleType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="nummer" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="nummer" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tisch"
})
@XmlRootElement(name = "Kellnersystem")
public class Kellnersystem {

	static int nextBestellNummer = 1;
	
    @XmlElement(name = "Tisch", required = true)
    protected List<Kellnersystem.Tisch> tisch;

    /**
     * Gets the value of the tisch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tisch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTisch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kellnersystem.Tisch }
     * 
     * 
     */
    
    public Kellnersystem addBestellungToNewKellnersystem(Kellnersystem.Tisch.Bestellungen.Bestellung bs) {
    	this.getTisch().add(new Kellnersystem.Tisch());
    	this.getTisch().get(0).setBestellungen(new Kellnersystem.Tisch.Bestellungen());
    	this.getTisch().get(0).getBestellungen().getBestellung().add(bs);
		return this;
    }
    
    public List<Kellnersystem.Tisch> getTisch() {
        if (tisch == null) {
            tisch = new ArrayList<Kellnersystem.Tisch>();
        }
        return this.tisch;
    }
    
    public Kellnersystem.Tisch getTisch(int tischNummer) {
    	for(int i=0; i < this.getTisch().size(); i++) {
    		if(this.getTisch().get(i).getNummer().compareTo(tischNummer) == 0) {
    			return this.getTisch().get(i);
    		}
    	}
    	throw (RuntimeException) null;
    }
    
    /**
     * Gibt Index des Tisches mit TischNummer
     * 
     * @return int
     *     
     */
    
    public int getIndex(int tischNummer) {
    	for(int i=0; i < this.getTisch().size(); i++) {
    		if(this.getTisch().get(i).getNummer().compareTo(tischNummer) == 0) {
    			return i;
    		}
    	}
    	throw (RuntimeException) null;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Bestellungen">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Bestellung" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Artikellist">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Artikel" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="Artikel_id">
     *                                                   &lt;simpleType>
     *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                                                       &lt;minInclusive value="0"/>
     *                                                     &lt;/restriction>
     *                                                   &lt;/simpleType>
     *                                                 &lt;/element>
     *                                                 &lt;element name="Menge">
     *                                                   &lt;simpleType>
     *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                                                       &lt;minInclusive value="0"/>
     *                                                     &lt;/restriction>
     *                                                   &lt;/simpleType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="nummer" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="nummer" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bestellungen"
    })
    public static class Tisch {

        @XmlElement(name = "Bestellungen", required = true)
        protected Kellnersystem.Tisch.Bestellungen bestellungen;
        @XmlAttribute
        protected Integer nummer;

        /**
         * Gets the value of the bestellungen property.
         * 
         * @return
         *     possible object is
         *     {@link Kellnersystem.Tisch.Bestellungen }
         *     
         */
        public Kellnersystem.Tisch.Bestellungen getBestellungen() {
            return bestellungen;
        }

        /**
         * Sets the value of the bestellungen property.
         * 
         * @param value
         *     allowed object is
         *     {@link Kellnersystem.Tisch.Bestellungen }
         *     
         */
        public void setBestellungen(Kellnersystem.Tisch.Bestellungen value) {
            this.bestellungen = value;
        }

        /**
         * Gets the value of the nummer property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNummer() {
            return nummer;
        }

        /**
         * Sets the value of the nummer property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNummer(Integer value) {
            this.nummer = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Bestellung" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Artikellist">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Artikel" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="Artikel_id">
         *                                         &lt;simpleType>
         *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *                                             &lt;minInclusive value="0"/>
         *                                           &lt;/restriction>
         *                                         &lt;/simpleType>
         *                                       &lt;/element>
         *                                       &lt;element name="Menge">
         *                                         &lt;simpleType>
         *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *                                             &lt;minInclusive value="0"/>
         *                                           &lt;/restriction>
         *                                         &lt;/simpleType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="nummer" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bestellung"
        })
        public static class Bestellungen {

            @XmlElement(name = "Bestellung", required = true)
            protected List<Kellnersystem.Tisch.Bestellungen.Bestellung> bestellung;

            /**
             * Gets the value of the bestellung property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the bestellung property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBestellung().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Kellnersystem.Tisch.Bestellungen.Bestellung }
             * 
             * 
             */
            public List<Kellnersystem.Tisch.Bestellungen.Bestellung> getBestellung() {
                if (bestellung == null) {
                    bestellung = new ArrayList<Kellnersystem.Tisch.Bestellungen.Bestellung>();
                }
                return this.bestellung;
            }

            public Kellnersystem.Tisch.Bestellungen.Bestellung getBestellung(int bestellNummer) {
            	for(int i=0; i < this.getBestellung().size(); i++) {
            		if(this.getBestellung().get(i).getNummer().compareTo(bestellNummer) == 0) {
            			return this.getBestellung().get(i);
            		}
            	}
        		return null;
            }

            public int getIndex(int bestellNummer) {
            	for(int i=0; i < this.getBestellung().size(); i++) {
            		if(this.getBestellung().get(i).getNummer().compareTo(bestellNummer) == 0) {
            			return i;
            		}
            	}
            	throw (RuntimeException) null;
            }
            
            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Artikellist">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Artikel" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="Artikel_id">
             *                               &lt;simpleType>
             *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
             *                                   &lt;minInclusive value="0"/>
             *                                 &lt;/restriction>
             *                               &lt;/simpleType>
             *                             &lt;/element>
             *                             &lt;element name="Menge">
             *                               &lt;simpleType>
             *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
             *                                   &lt;minInclusive value="0"/>
             *                                 &lt;/restriction>
             *                               &lt;/simpleType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="nummer" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "artikellist"
            })
            public static class Bestellung {

                @XmlElement(name = "Artikellist", required = true)
                protected Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist artikellist;
                @XmlAttribute
                protected Integer nummer;

                /**
                 * Gets the value of the artikellist property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist }
                 *     
                 */
                public Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist getArtikellist() {
                    return artikellist;
                }

                /**
                 * Sets the value of the artikellist property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist }
                 *     
                 */
                public void setArtikellist(Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist value) {
                    this.artikellist = value;
                }

                /**
                 * Gets the value of the nummer property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getNummer() {
                    return nummer;
                }

//                /**
//                 * Sets the value of the nummer property.
//                 * 
//                 * @param value
//                 *     allowed object is
//                 *     {@link Integer }
//                 *     
//                 */
//                public void setNummer(Integer value) {
//                    this.nummer = value;
//                }
                
                /**
                * setzt noch nicht vergebene bestellNummer
                * 
              	*     
              	*/
                
                public void setNummer() {
                	this.nummer = nextBestellNummer++;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Artikel" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="Artikel_id">
                 *                     &lt;simpleType>
                 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
                 *                         &lt;minInclusive value="0"/>
                 *                       &lt;/restriction>
                 *                     &lt;/simpleType>
                 *                   &lt;/element>
                 *                   &lt;element name="Menge">
                 *                     &lt;simpleType>
                 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
                 *                         &lt;minInclusive value="0"/>
                 *                       &lt;/restriction>
                 *                     &lt;/simpleType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "artikel"
                })
                public static class Artikellist {

                    @XmlElement(name = "Artikel", required = true)
                    protected List<Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist.Artikel> artikel;

                    /**
                     * Gets the value of the artikel property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the artikel property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getArtikel().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist.Artikel }
                     * 
                     * 
                     */
                    public List<Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist.Artikel> getArtikel() {
                        if (artikel == null) {
                            artikel = new ArrayList<Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist.Artikel>();
                        }
                        return this.artikel;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="Artikel_id">
                     *           &lt;simpleType>
                     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
                     *               &lt;minInclusive value="0"/>
                     *             &lt;/restriction>
                     *           &lt;/simpleType>
                     *         &lt;/element>
                     *         &lt;element name="Menge">
                     *           &lt;simpleType>
                     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
                     *               &lt;minInclusive value="0"/>
                     *             &lt;/restriction>
                     *           &lt;/simpleType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "artikelId",
                        "menge"
                    })
                    public static class Artikel {

                        @XmlElement(name = "Artikel_id")
                        protected int artikelId;
                        @XmlElement(name = "Menge", required = true)
                        protected int menge;

                        /**
                         * Gets the value of the artikelId property.
                         * 
                         */
                        public int getArtikelId() {
                            return artikelId;
                        }

                        /**
                         * Sets the value of the artikelId property.
                         * 
                         */
                        public void setArtikelId(int value) {
                            this.artikelId = value;
                        }

                        /**
                         * Gets the value of the menge property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigDecimal }
                         *     
                         */
                        public int getMenge() {
                            return menge;
                        }

                        /**
                         * Sets the value of the menge property.
                         * 
                         * @param i
                         *     allowed object is
                         *     {@link BigDecimal }
                         *     
                         */
                        public void setMenge(int i) {
                            this.menge = i;
                        }

                    }

                }

            }

        }

    }

}
