//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.18 at 08:28:08 PM MESZ 
//


package com.kellnersystem.main;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kellnersystem.main package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kellnersystem.main
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist.Artikel }
     * 
     */
    public Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist.Artikel createKellnersystemTischBestellungenBestellungArtikellistArtikel() {
        return new Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist.Artikel();
    }

    /**
     * Create an instance of {@link Kellnersystem }
     * 
     */
    public Kellnersystem createKellnersystem() {
        return new Kellnersystem();
    }

    /**
     * Create an instance of {@link Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist }
     * 
     */
    public Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist createKellnersystemTischBestellungenBestellungArtikellist() {
        return new Kellnersystem.Tisch.Bestellungen.Bestellung.Artikellist();
    }

    /**
     * Create an instance of {@link Kellnersystem.Tisch.Bestellungen.Bestellung }
     * 
     */
    public Kellnersystem.Tisch.Bestellungen.Bestellung createKellnersystemTischBestellungenBestellung() {
        return new Kellnersystem.Tisch.Bestellungen.Bestellung();
    }

    /**
     * Create an instance of {@link Kellnersystem.Tisch.Bestellungen }
     * 
     */
    public Kellnersystem.Tisch.Bestellungen createKellnersystemTischBestellungen() {
        return new Kellnersystem.Tisch.Bestellungen();
    }

    /**
     * Create an instance of {@link Kellnersystem.Tisch }
     * 
     */
    public Kellnersystem.Tisch createKellnersystemTisch() {
        return new Kellnersystem.Tisch();
    }

}
