//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 06:56:49 PM MESZ 
//


package com.kellnersystem.artikelliste;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Artikel" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ArtikelName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="100"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Preis">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="artikelId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "artikel"
})
@XmlRootElement(name = "Artikelliste")
public class Artikelliste {

    @XmlElement(name = "Artikel", required = true)
    protected List<Artikelliste.Artikel> artikel;

    /**
     * Gets the value of the artikel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artikel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArtikel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Artikelliste.Artikel }
     * 
     * 
     */
    public List<Artikelliste.Artikel> getArtikel() {
        if (artikel == null) {
            artikel = new ArrayList<Artikelliste.Artikel>();
        }
        return this.artikel;
    }
    public Artikelliste.Artikel getArtikel(int ArtikelId) {
    	for(int i = 0; i < this.getArtikel().size(); i++) {
    		if(this.getArtikel().get(i).getArtikelId().compareTo(ArtikelId) == 0) {
    			return this.getArtikel().get(i);
    		}
    	}
    	throw (RuntimeException) null;
    }
    
    public int getIndex(int ArtikelId) {
    	for(int i=0; i < this.getArtikel().size(); i++) {
    		if(this.getArtikel().get(i).getArtikelId().compareTo(ArtikelId) == 0) {
    			return i;
    		}
    	}
    	throw (RuntimeException) null;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ArtikelName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="100"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Preis">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="artikelId" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "artikelName",
        "preis"
    })
    public static class Artikel {

        @XmlElement(name = "ArtikelName", required = true)
        protected String artikelName;
        @XmlElement(name = "Preis", required = true)
        protected double preis;
        @XmlAttribute
        protected Integer artikelId;

        /**
         * Gets the value of the artikelName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArtikelName() {
            return artikelName;
        }

        /**
         * Sets the value of the artikelName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArtikelName(String value) {
            this.artikelName = value;
        }

        /**
         * Gets the value of the preis property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public double getPreis() {
            return preis;
        }

        /**
         * Sets the value of the preis property.
         * 
         * @param d
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPreis(double d) {
            this.preis = d;
        }

        /**
         * Gets the value of the artikelId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getArtikelId() {
            return artikelId;
        }

        /**
         * Sets the value of the artikelId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setArtikelId(Integer value) {
            this.artikelId = value;
        }

    }

}
